import Head from "next/head";
import Link from "next/link";
import type { GetServerSideProps } from "next";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { hasValidSession } from "../lib/session";

type Candidate={page_id:string;page_name:string;instagram_account_id?:string|null;tasks?:string[]};
type Bound={account_id:string;label?:string;approved_by?:string;bound_at?:string};
type Asset={uri:string;sha256:string;provenance:string;media_type:string};
async function jsonFetch(url:string,init?:RequestInit){const r=await fetch(url,init);const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.detail||data.error||`Request failed (${r.status})`);return data;}
export default function Publisher(){
 const[status,setStatus]=useState<any>(null),[candidates,setCandidates]=useState<Candidate[]>([]),[notice,setNotice]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState("");
 const[approvedBy,setApprovedBy]=useState(""),[selectedPage,setSelectedPage]=useState(""),[confirmBind,setConfirmBind]=useState(false);
 const[platform,setPlatform]=useState("facebook"),[accountId,setAccountId]=useState(""),[campaignId,setCampaignId]=useState(""),[caption,setCaption]=useState(""),[destination,setDestination]=useState(""),[scheduledAt,setScheduledAt]=useState(""),[assets,setAssets]=useState<Asset[]>([]);
 const[receiptKey,setReceiptKey]=useState(""),[receipt,setReceipt]=useState<any>(null);
 const bound:Bound[]=status?.accounts?.bound_accounts?.[platform]||[];
 useEffect(()=>{if(bound.length&&!bound.some(x=>x.account_id===accountId))setAccountId(bound[0].account_id);if(!bound.length)setAccountId("");},[platform,status]);
 const readyToQueue=useMemo(()=>Boolean(campaignId.trim()&&accountId&&caption.trim()&&destination.trim()),[campaignId,accountId,caption,destination]);
 async function refresh(){setError("");try{const[s,c]=await Promise.all([jsonFetch("/api/publisher/status"),jsonFetch("/api/publisher/meta/candidates")]);setStatus(s);setCandidates(c.candidates||[]);}catch(e){setError(e instanceof Error?e.message:"Refresh failed");}}
 useEffect(()=>{void refresh();},[]);
 async function beginMeta(){setBusy("meta");setError("");try{const d=await jsonFetch("/api/publisher/meta/start",{method:"POST"});if(!d.authorization_url)throw new Error("Authorization URL missing");window.location.assign(d.authorization_url);}catch(e){setError(e instanceof Error?e.message:"Meta authorization failed");setBusy("");}}
 async function bind(){if(!confirmBind)return;setBusy("bind");setError("");setNotice("");try{await jsonFetch("/api/publisher/meta/bind",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({page_id:selectedPage,approved_by:approvedBy,human_approval:"APPROVED"})});setNotice("Account binding recorded with explicit human approval.");setConfirmBind(false);setSelectedPage("");await refresh();}catch(e){setError(e instanceof Error?e.message:"Binding failed");}finally{setBusy("");}}
 function addAsset(){setAssets([...assets,{uri:"",sha256:"",provenance:"operator",media_type:"application/octet-stream"}]);}
 async function queue(e:FormEvent){e.preventDefault();setBusy("queue");setError("");setNotice("");setReceipt(null);try{const d=await jsonFetch("/api/publisher/jobs/queue",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({campaign_id:campaignId,platform,account_id:accountId,caption,destination_url:destination,scheduled_at:scheduledAt?new Date(scheduledAt).toISOString():null,assets})});setNotice(`Queued with status ${d.status}. No live publish was attempted.`);setReceiptKey(d.idempotency_key||"");if(d.idempotency_key)setReceipt(await jsonFetch(`/api/publisher/receipts/${encodeURIComponent(d.idempotency_key)}`));}catch(e){setError(e instanceof Error?e.message:"Queue failed");}finally{setBusy("");}}
 async function lookup(e:FormEvent){e.preventDefault();setBusy("receipt");setError("");try{setReceipt(await jsonFetch(`/api/publisher/receipts/${encodeURIComponent(receiptKey.trim())}`));}catch(e){setError(e instanceof Error?e.message:"Receipt lookup failed");}finally{setBusy("");}}
 return <><Head><title>Dominion Publisher — Control</title><meta name="robots" content="noindex,nofollow" /></Head><div className="appShell"><header className="topbar"><div className="brand"><span className="brandMark small">D</span><div><strong>Dominion Publisher</strong><span>Governed operator surface</span></div></div><Link className="button ghost" href="/">Overview</Link></header><main className="content">
 <section className="pageTitle"><div><p className="overline">PUBLISHER</p><h1>Connect, approve, queue, prove.</h1><p>Every consequential action is explicit. Credentials stay server-side and live Meta publishing remains held closed.</p></div><button className="button secondary" onClick={refresh} disabled={!!busy}>Refresh status</button></section>
 {error&&<div className="alert danger">{error}</div>}{notice&&<div className="alert success">{notice}</div>}
 <section className="metricGrid compact"><article className="metric"><span>Service</span><strong>{status?.health?.status==="ok"?"ONLINE":"—"}</strong></article><article className="metric"><span>Meta app</span><strong>{status?.health?.meta_app_configured?"READY":"NOT READY"}</strong></article><article className="metric"><span>Facebook</span><strong>{status?.health?.meta_bound_counts?.facebook??"—"}</strong></article><article className="metric"><span>Instagram</span><strong>{status?.health?.meta_bound_counts?.instagram??"—"}</strong></article></section>
 <section className="panel"><div className="sectionHead"><div><p className="overline">1 · IDENTITY</p><h2>Meta account authorization</h2></div><span className="status hold">LIVE PUBLISH HOLD</span></div><p className="muted">OAuth authorization creates candidates only. Binding still requires explicit operator approval below.</p><button className="button secondary" onClick={beginMeta} disabled={busy==="meta"||!status?.health?.meta_app_configured}>{busy==="meta"?"Opening Meta…":"Authorize Meta account"}</button>
 {candidates.length>0&&<div className="approvalBox"><h3>Pending binding candidates</h3><div className="candidateList">{candidates.map(c=><label className={`candidate ${selectedPage===c.page_id?"selected":""}`} key={c.page_id}><input type="radio" name="candidate" checked={selectedPage===c.page_id} onChange={()=>setSelectedPage(c.page_id)}/><div><strong>{c.page_name}</strong><span>Facebook {c.page_id}{c.instagram_account_id?` · Instagram ${c.instagram_account_id}`:""}</span></div></label>)}</div><div className="formGrid"><label><span>Approved by</span><input value={approvedBy} onChange={e=>setApprovedBy(e.target.value)} placeholder="Operator name"/></label></div><label className="check"><input type="checkbox" checked={confirmBind} onChange={e=>setConfirmBind(e.target.checked)}/><span>I explicitly approve binding this selected Page to Dominion Publisher.</span></label><button className="button primary" onClick={bind} disabled={!selectedPage||!approvedBy.trim()||!confirmBind||busy==="bind"}>{busy==="bind"?"Binding…":"Bind approved account"}</button></div>}</section>
 <section className="panel"><div className="sectionHead"><div><p className="overline">2 · JOB</p><h2>Queue governed content</h2></div><span className="status ok">QUEUE ONLY</span></div><form className="stack" onSubmit={queue}><div className="formGrid two"><label><span>Platform</span><select value={platform} onChange={e=>setPlatform(e.target.value)}><option value="facebook">Facebook</option><option value="instagram">Instagram</option></select></label><label><span>Bound account</span><select value={accountId} onChange={e=>setAccountId(e.target.value)} disabled={!bound.length}><option value="">{bound.length?"Select account":"No bound account"}</option>{bound.map(x=><option key={x.account_id} value={x.account_id}>{x.label||x.account_id}</option>)}</select></label></div><div className="formGrid two"><label><span>Campaign ID</span><input value={campaignId} onChange={e=>setCampaignId(e.target.value)} placeholder="campaign-2026-09" required/></label><label><span>Schedule (optional)</span><input type="datetime-local" value={scheduledAt} onChange={e=>setScheduledAt(e.target.value)}/></label></div><label><span>Caption</span><textarea rows={6} value={caption} onChange={e=>setCaption(e.target.value)} placeholder="Final approved content" required/></label><label><span>Destination URL</span><input type="url" value={destination} onChange={e=>setDestination(e.target.value)} placeholder="https://…" required/></label>
 <div className="sectionHead minor"><div><h3>Assets</h3><p className="muted">Optional. Each asset requires immutable SHA-256 provenance.</p></div><button type="button" className="button ghost" onClick={addAsset}>Add asset</button></div>{assets.map((a,i)=><div className="asset" key={i}><div className="formGrid two"><label><span>Asset URI</span><input value={a.uri} onChange={e=>setAssets(assets.map((x,j)=>j===i?{...x,uri:e.target.value}:x))}/></label><label><span>Media type</span><input value={a.media_type} onChange={e=>setAssets(assets.map((x,j)=>j===i?{...x,media_type:e.target.value}:x))}/></label></div><label><span>SHA-256</span><input value={a.sha256} maxLength={64} onChange={e=>setAssets(assets.map((x,j)=>j===i?{...x,sha256:e.target.value}:x))}/></label><div className="assetFoot"><label><span>Provenance</span><input value={a.provenance} onChange={e=>setAssets(assets.map((x,j)=>j===i?{...x,provenance:e.target.value}:x))}/></label><button type="button" className="textButton dangerText" onClick={()=>setAssets(assets.filter((_,j)=>j!==i))}>Remove</button></div></div>)}
 <div className="holdAction"><div><strong>Live publish is disabled by governance.</strong><span>Queueing produces an auditable receipt without creating a public post.</span></div><button className="button primary" disabled={!readyToQueue||busy==="queue"}>{busy==="queue"?"Queueing…":"Queue and verify receipt"}</button></div></form></section>
 <section className="panel"><div><p className="overline">3 · PROOF</p><h2>Receipt verification</h2></div><form className="receiptLookup" onSubmit={lookup}><input value={receiptKey} onChange={e=>setReceiptKey(e.target.value)} placeholder="Idempotency key"/><button className="button secondary" disabled={!receiptKey.trim()||busy==="receipt"}>{busy==="receipt"?"Checking…":"Verify"}</button></form>{receipt&&<pre className="receipt">{JSON.stringify(receipt,null,2)}</pre>}</section>
 </main></div></>;
}
export const getServerSideProps:GetServerSideProps=async({req})=>hasValidSession(req)?{props:{}}:{redirect:{destination:"/login",permanent:false}};
